### PR TITLE
Setup knitweb on windows

### PR DESCRIPTION
**Pull request by shiluka**

### CODE REVIEW

**Comment by tian2992** [comment]
Binaries should never be committed to the repo.

**Comment by tian2992** [comment]
http://robinwinslow.co.uk/2013/06/11/dont-ever-commit-binary-files-to-git/

**Comment by shiluka** [comment]
@tian2992 Hi, I have some doubt regarding this article, We can use git for fully version control, git is not used only for compare text files and store them. So any given time if you want to go back to a specific commit, build should be in a working state. In real time any software project is bundle with binary resources that can be lost if not controlled.  As my opinion any file that is used to the build process to generate a product should be version controlled as sometimes it possible to revert to an earlier release.  Using git is not just comparing changes. Thank you.

**Comment by tian2992** [comment]
Yes, for that we use **build scripts**. Therefore we ensure the build environment is standardized with the version that is needed but we avoid injecting unnecessary blobs and dependencies. Imagine if I had checked in Flask's source into the repo or added Node.js' binaries to Knitweb repo. Instead we use the setup.py to ensure the proper dependencies are installed (and the proper versions) and ready to build.

We can keep the state of the repo and make it ready to build at any time, we do not need to bundle the tools for the build.

**Pull request merged**
